[".oh-my-zsh"]
    type = "archive"
    url = "https://github.com/ohmyzsh/ohmyzsh/archive/master.tar.gz"
    stripComponents = 1
    refreshPeriod = "168h"
    exclude = [
        "*/custom",
    ]
[".oh-my-zsh/custom/plugins/zsh-syntax-highlighting"]
    type = "archive"
    url = "https://github.com/zsh-users/zsh-syntax-highlighting/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".tmux/plugins/tpm"]
    type = "archive"
    url = "https://github.com/tmux-plugins/tpm/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".vim/pack/vihang/opt/solarized8"]
    type = "archive"
    url = "https://codeberg.org/lifepillar/vim-solarized8/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
[".vim/pack/vihang/start/vim-indent-guides"]
    type = "archive"
    url = "https://github.com/preservim/vim-indent-guides/archive/master.tar.gz"
    exact = true
    stripComponents = 1
    refreshPeriod = "168h"
